# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='croco',
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='etest.Course'),
        ),
    ]
